import {readFileSync} from 'node:fs';
import http from 'node:http';
import {av01FirstPage,av01Meta,av01SignedPlaylist} from './av01-test-hook.js';
const verified=JSON.parse(readFileSync(new URL('./data/catalog-verified.json',import.meta.url),'utf8'));
const verifiedMetadata=JSON.parse(readFileSync(new URL('./data/metadata-verified-nuvio.json',import.meta.url),'utf8'));
const ikisodaLocal=JSON.parse(readFileSync(new URL('./data/ikisoda-catalog.json',import.meta.url),'utf8'));
const IKISODA_CATALOG_URL='https://raw.githubusercontent.com/chuongnguyen89dn-ui/missav/ikisoda-data/data/ikisoda-catalog.json';let ikisodaCache={data:ikisodaLocal,at:0};
async function getIkisodaCatalog(){const now=Date.now();if(now-ikisodaCache.at<15000)return ikisodaCache.data;try{const r=await fetch(IKISODA_CATALOG_URL+'?v='+Math.floor(now/15000),{headers:{'User-Agent':'missav-nuvio-addon'},signal:AbortSignal.timeout(8000)});if(r.ok)ikisodaCache={data:await r.json(),at:now}}catch(e){console.error('[IKISODA]',e.message)}ikisodaCache.at=now;return ikisodaCache.data}
const filmById=new Map(verified.map(f=>['missav:'+f.code.toLowerCase(),f]));
function uniq(a){return [...new Set((a||[]).map(x=>typeof x==='string'?x:x?.name).filter(Boolean))]}
function filmMeta(f){const m=verifiedMetadata[f.code]||{},date=m.release_date||f.release_date||'',genres=uniq(m.genres).length?uniq(m.genres):(f.genres||'').split(',').map(x=>x.trim()).filter(Boolean);return {id:'missav:'+f.code.toLowerCase(),type:'movie',name:m.title||f.title||f.code,poster:m.poster||f.poster,posterShape:'poster',description:m.description||f.description,releaseInfo:date?date.slice(0,4):undefined,genres,cast:uniq(m.actresses),director:uniq(m.directors),language:'Tiếng Nhật'}}
function normalizeIki(x){const code=String(x?.code||x?.id||'').replace(/^ikisoda:/i,'').trim();return code?{...x,id:x.id||'ikisoda:'+code.toLowerCase(),name:x.name||x.title||code,source_page:x.source_page||x.url}:null}
async function ikiMovies(){const c=await getIkisodaCatalog();return (Array.isArray(c)?c:(c?.movies||[])).map(normalizeIki).filter(Boolean)}
function ikiMeta(x){return {id:x.id,type:'movie',name:x.name,poster:x.poster,posterShape:'poster',description:[x.code,x.studio,x.duration].filter(Boolean).join(' · '),genres:x.genres||[],language:'Tiếng Nhật'}}
function publicStream(f){const s=(f.streams_1080||[]).find(x=>x.quality==='1080p'&&x.verification==='master_resolution_1080');if(!s)return[];const u=new URL(s.url);return [{name:'Mirror 1080p · DIRECT',url:'https://surrit.mrstcdn.store'+u.pathname+u.search,behaviorHints:{notWebReady:true,proxyHeaders:{request:{Referer:f.url||'https://missav.ws/','Origin':'https://missav.ws','User-Agent':'Mozilla/5.0'}}}}]}
const manifest={id:'community.missav.hls.test',version:'0.5.0',name:'MissAV 1080p',description:'MissAV + IkiSoda + AV01 test',resources:['catalog','meta','stream'],types:['movie'],catalogs:[{type:'movie',id:'missav-1080',name:'MissAV · Verified 1080p'},{type:'movie',id:'ikisoda',name:'ikisoda'},{type:'movie',id:'av01-test',name:'Test AV01'}],idPrefixes:['missav:','ikisoda:','av01:']};
const cors={'access-control-allow-origin':'*','access-control-allow-methods':'GET, HEAD, OPTIONS','access-control-allow-headers':'*'};function json(res,data,status=200){const body=JSON.stringify(data);res.writeHead(status,{...cors,'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(body)});res.end(body)}async function av01ById(id){return (await av01FirstPage()).find(x=>String(x.id)===String(id))}
http.createServer(async(req,res)=>{const path=decodeURIComponent(new URL(req.url,'http://localhost').pathname);try{if(req.method==='OPTIONS'){res.writeHead(204,cors);return res.end()}if(path==='/'||path==='/health')return json(res,{status:'ok',verified:verified.length,av01:'Test AV01 enabled'});if(path==='/manifest.json')return json(res,manifest);if(path==='/catalog/movie/missav-1080.json')return json(res,{metas:verified.map(filmMeta)});if(path==='/catalog/movie/ikisoda.json')return json(res,{metas:(await ikiMovies()).map(ikiMeta)});if(path==='/catalog/movie/av01-test.json')return json(res,{metas:(await av01FirstPage()).map(av01Meta)});if(path.startsWith('/meta/movie/missav:')&&path.endsWith('.json')){const f=filmById.get(path.slice('/meta/movie/'.length,-5));return f?json(res,{meta:filmMeta(f)}):json(res,{error:'Not found'},404)}if(path.startsWith('/stream/movie/missav:')&&path.endsWith('.json')){const f=filmById.get(path.slice('/stream/movie/'.length,-5));return json(res,{streams:f?publicStream(f):[]})}if(path.startsWith('/meta/movie/ikisoda:')&&path.endsWith('.json')){const id=path.slice('/meta/movie/'.length,-5),x=(await ikiMovies()).find(v=>v.id===id);return x?json(res,{meta:ikiMeta(x)}):json(res,{error:'Not found'},404)}if(path.startsWith('/stream/movie/ikisoda:')&&path.endsWith('.json')){const id=path.slice('/stream/movie/'.length,-5),x=(await ikiMovies()).find(v=>v.id===id);return json(res,{streams:x?.url?[{name:'IkiSoda 1080p',url:x.url,behaviorHints:{notWebReady:true,proxyHeaders:{request:{Referer:x.source_page||'https://ikisoda.com/','User-Agent':'Mozilla/5.0'}}}}]:[]})}if(path.startsWith('/meta/movie/av01:')&&path.endsWith('.json')){const id=path.slice('/meta/movie/av01:'.length,-5),x=await av01ById(id);return x?json(res,{meta:av01Meta(x)}):json(res,{error:'Not found'},404)}if(path.startsWith('/stream/movie/av01:')&&path.endsWith('.json')){const id=path.slice('/stream/movie/av01:'.length,-5),x=await av01ById(id);if(!x)return json(res,{streams:[]});const proto=req.headers['x-forwarded-proto']||'https';return json(res,{streams:[{name:'AV01 · signed HLS test',title:'AV01 direct CDN playlist',url:`${proto}://${req.headers.host}/av01/${encodeURIComponent(id)}/master.m3u8`,behaviorHints:{notWebReady:true}}]})}if(path.startsWith('/av01/')&&path.endsWith('/master.m3u8')){const id=path.split('/')[2],body=await av01SignedPlaylist(id);res.writeHead(200,{...cors,'content-type':'application/vnd.apple.mpegurl','cache-control':'no-store','content-length':Buffer.byteLength(body)});return res.end(req.method==='HEAD'?'':body)}return json(res,{error:'Not found'},404)}catch(e){console.error('[REQUEST_ERROR]',path,e);return json(res,{error:e.message||'Internal error'},502)}}).listen(Number(process.env.PORT||3000),'0.0.0.0',()=>console.log('MissAV addon listening'));
